
services:

  nginx:
    
    build: ./requirements/nginx/
    ports:
      - 127.0.0.1:443:443
    working_dir: /requirements/nginx
    

#   mariadb:

#     build: ./requirements/mariadb/
  
#   wordpress:

#     build: ./requirements/wordpress/

# volumes: