
services:

  nginx:
    
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - 127.0.0.1:443:443 # diff between ports & expose; ports -> host machine and beyond; expose -> between containers
    expose:
      - 9000
    working_dir: /requirements/nginx
    restart: always
    volumes:
      - wordpress_fs:/var/www/html/wordpress
    networks:
      - inception
    env_file:
      - .env

  mariadb:

    build: ./requirements/mariadb/
    container_name: mariadb
    expose:
      - 3306
    working_dir: /requirements/mariadb
    restart: always
    networks:
      - inception
    volumes:
      - wordpress_db:/var/lib/mysql # this is the directory in the container
    env_file:
      - .env

  wordpress:

    build: ./requirements/wordpress/
    container_name: wordpress
    expose:
      - 3306
      - 9000
    working_dir: /requirements/wordpress
    restart: always
    networks:
      - inception
    volumes:
      - wordpress_fs:/var/www/html/wordpress
    env_file:
      - .env

volumes:
  wordpress_db:
    name: wordpress_database
    driver: local # use os driver
    driver_opts:
      type: none
      o: bind # mount type
      device: /home/laian/data/wordpress_database # mountpoint??

  wordpress_fs:
    name: wordpress_files
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/laian/data/wordpress_files

networks:
  inception:
